Question #1

In [1]:
import numpy as np

a = np.array([3,4])

b = np.array([1,-2])

print(a + b)

[4 2]


Question #2

In [4]:
import numpy as np

v = np.array([6,2])
w = np.array([3,5])
print(np.dot(v,w))

28


Question #3

In [12]:
import numpy as np 

M = np.array([[3,6,1],
              [1,5,4]])
N = np.array([[2,2,5],
             [3,1,2]])
print(M+N)

[[5 8 6]
 [4 6 6]]


Question #4

In [13]:
import numpy as np

P = np.array([[7,2],
             [3,5]])
Q = np.array([[9,4],
             [3,1]])
print(np.dot(P,Q))

[[69 30]
 [42 17]]


Question #5

In [15]:
import numpy as np

S = np.array([[5,3],
             [6,4]])
T = np.array([[1,4],
             [2,6]])

print(np.linalg.inv(S) @ T)

[[-1. -1.]
 [ 2.  3.]]
